# Generated by Django 3.2.6 on 2021-08-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('roll_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=10)),
                ('school_name', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='studentacademics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maths', models.CharField(max_length=10)),
                ('physics', models.CharField(max_length=10)),
                ('chemistry', models.CharField(max_length=10)),
                ('biology', models.CharField(max_length=10)),
                ('english', models.CharField(max_length=10)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.students')),
            ],
        ),
    ]
