# Generated by Django 3.2.6 on 2021-08-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll_number',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
